# @Author: Daniel Gomes
# @Date:   2022-10-08 13:47:48
# @Last Modified by:   Daniel Gomes
# @Last Modified time: 2022-10-08 14:59:02
site_name: Preparação da Dissertação
repo_url: https://github.com/DanielGomes14/PD
repo_name: Preparação da Dissertação

theme:
   name: material
   favicon: assets/favicon.ico
   logo: assets/logo.png
   palette:
      primary: light blue
      accent: light blue
   features:
    - navigation.instant
    - navigation.top

